name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker eu.gcr.io

      - name: Debug Environment Variables
        run: env | grep GCP

      - name: Build and push backend Docker image
        run: |
          docker build -t eu.gcr.io/${{ env.GCP_PROJECT }}/predictive-maintenance-backend:latest -f backend/Dockerfile .
          docker push eu.gcr.io/${{ env.GCP_PROJECT }}/predictive-maintenance-backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t eu.gcr.io/${{ env.GCP_PROJECT }}/predictive-maintenance-frontend:latest -f frontend/Dockerfile .
          docker push eu.gcr.io/${{ env.GCP_PROJECT }}/predictive-maintenance-frontend:latest

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy predictive-maintenance-backend \
            --image eu.gcr.io/${{ env.GCP_PROJECT }}/predictive-maintenance-backend:latest \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --vpc-connector my-vpc-connector \
            --timeout 600s \
            --verbosity debug

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy predictive-maintenance-frontend \
            --image eu.gcr.io/${{ env.GCP_PROJECT }}/predictive-maintenance-frontend:latest \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated \
            --vpc-connector my-vpc-connector \
            --timeout 600s \
            --verbosity debug
