name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/predictive-maintenance:latest .
          docker push gcr.io/${{ env.PROJECT_ID }}/predictive-maintenance:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy predictive-maintenance \
            --image gcr.io/${{ env.PROJECT_ID }}/predictive-maintenance:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
